# Generated by Django 5.0.6 on 2024-06-20 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BusStopDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M3FinderApp.busstop')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bus_stops', models.ManyToManyField(through='M3FinderApp.BusStopDestination', to='M3FinderApp.busstop')),
            ],
        ),
        migrations.AddField(
            model_name='busstopdestination',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M3FinderApp.destination'),
        ),
        migrations.AlterUniqueTogether(
            name='busstopdestination',
            unique_together={('bus_stop', 'destination')},
        ),
    ]
