# Generated by Django 5.0.6 on 2024-06-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M3FinderApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
