# Generated by Django 5.0.6 on 2024-07-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M3FinderApp', '0002_destinationsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationsubmission',
            name='additional_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destinationsubmission',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destinationsubmission',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='destinationsubmission',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='destinationsubmission',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
